[platformio]
data_dir = ../web

[env:esp32dev]
platform = espressif32@6.9.0
board = esp32dev
framework = arduino
board_build.filesystem = littlefs
monitor_speed = 115200
lib_deps =
    esp32async/AsyncTCP@3.3.2
    esp32async/ESPAsyncWebServer@3.6.0
build_unflags = -std=gnu++11
build_flags =
    -std=gnu++17
    -DCORE_DEBUG_LEVEL=0

[env:esp32dev-demo]
extends = env:esp32dev
build_flags =
    ${env:esp32dev.build_flags}
    -DSOULDRIVE_DEMO=1
